[tools]
aws = "latest"
curlie = "latest"
flutter = "latest"
gemini = "latest"
go = "latest"
java = "temurin-17"
neovim = "latest"
node = "lts"
opencode = "latest"
pnpm = "latest"
python = "latest"
uv = "latest"
starship = "latest"
lazygit = "latest"
lazydocker = "latest"
ripgrep = "latest"
zoxide = "latest"
fd = "latest"
eza = "latest"
gh = "latest"
stylua = "latest"
yazi = "latest"
chezmoi = "latest"
